bitlbee:
    image: kalbasit/bitlbee
    expose:
        - "6667"

weechat:
    build: .
    tty: true
    environment:
        PASSWORD: hunter2
    ports:
        - "9001:9001"
    links:
        - bitlbee
